---
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: example.nginx
      image: chrismeyers/centos7
      image_version: latest
      ansible_groups:
        - group1
verifier:
  name: testinfra
