---
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: centos-7.2
      box: bento/centos-7.2
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 2
  instances:
    - name: example.mariadb
      ansible_groups:
        - dbservers
verifier:
  name: testinfra
