---
- name: Install Nginx
  hosts: webservers
  become: true
  vars:
    use_epel: true
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    nginx_conf_file_path: /etc/nginx/nginx.conf
    nginx_port: 80
    nginx_docroot: "/opt/www"
  tasks:
    - name: Enable nginx repo.
      template:
        src: templates/nginx.repo.j2
        dest: /etc/yum.repos.d/nginx.repo
        owner: root
        group: root
        mode: 0644
      when: not {{ use_epel|bool }}

    - block:
      - name: Install EPEL repo.
        yum:
          name: "{{ epel_repo_url }}"
          state: present

      - name: Import EPEL GPG key.
        rpm_key:
          key: "{{ epel_repo_gpg_key_url }}"
          state: present
        ignore_errors: "{{ ansible_check_mode }}"
      when: "{{ use_epel|bool }} == true"


    - name: Ensure nginx is installed.
      yum: name=nginx state=installed
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Copy nginx configuration in place.
      template:
        src: nginx.conf.j2
        dest: "{{ nginx_conf_file_path }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - reload nginx
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Ensure nginx is started and enabled to start at boot.
      service: name=nginx state=started enabled=yes
      ignore_errors: "{{ ansible_check_mode }}"

    - block:
      - name: create docroot
        file: name="{{ nginx_docroot }}" state=directory
      - name: create index.html
        template: src=files/index-nginx-example.html.j2 dest={{ nginx_docroot }}/index.html
      tags: myapp

  handlers:
    - name: reload nginx
      service: name=nginx state=restarted
