---
- hosts: all
  gather_facts: true

- hosts: webservers
  serial: 1
  become: true
  tasks:
    - name: disable the server in haproxy
      haproxy: 'state=disabled backend=habackend host={{ inventory_hostname }} socket=/var/lib/haproxy/stats'
      delegate_to: "{{ item }}"
      with_items: "{{ groups.loadbal }}"

    - name: update myapp
      include_role: name=example.myapp

    - pause: seconds=40

    - name: wait for webserver to come up
      wait_for: port=80 timeout=80

    - name: enable the server in haproxy
      haproxy: 'state=enabled backend=habackend host={{ inventory_hostname }} socket=/var/lib/haproxy/stats'
      delegate_to: "{{ item }}"
      with_items: "{{ groups.loadbal }}"
